### PR TITLE
Add meson option for default timeout

### PR DESCRIPTION
**Pull request by jcorporation**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
It should be obvious what unit is expected; for a programmer, milliseconds is a commonly used unit for timeouts, but for users, that's surprising.

**Comment by MaxKellermann** [comment]
Also why would you want to modify the default timeout at compile time?

**Comment by jcorporation** [comment]
Other default settings are also configurable at compile time. Why not the timeout?

**Comment by MaxKellermann** [comment]
It matters little how the macro is named, but yes, with a suffix it's better; I care most about the level the user can see, and your addition to meson_options.txt leaves the user clueless what the parameter value means.
And I still doubt that the option is useful at all.

**Comment by jcorporation** [comment]
> And I still doubt that the option is useful at all.

Then let's not waste any working time, it is also not very important for me.

**Pull request closed without merging**
