### PR TITLE
Add support for the OriginalDate tag

### PR DESCRIPTION
**Pull request by tremby**
This tag is useful when the user would like all releases of the same album to be sorted next to each other.

This corresponds to https://github.com/MaxKellermann/MPD/pull/29

### CODE REVIEW

**Comment by tremby** [comment]
Please ignore for now; see the referenced MPD pull request for details.

**Comment by tremby** [comment]
Ready for review.

**Comment by MaxKellermann** [comment]
New tags must never be added in the middle, because this is an ABI change. Move it to the end.

**Comment by tremby** [comment]
Yikes, I see the comment saying exactly this in tag.h now. Sorry for not noticing that before.

**Comment by MaxKellermann** [comment]
Sigh. Just to let you know: your commit caused an ABI breakage. Binaries compiled with libmpdclient 2.11 are now incompatible with version 2.12+. To prevent this, there is a big fat warning just a few lines below your change:

	/* IMPORTANT: the ordering of tag types above must be
	   retained, or else the libmpdclient ABI breaks */

**Comment by tremby** [comment]
Argh. You had already pointed this out [above](https://github.com/MusicPlayerDaemon/libmpdclient/pull/1#issuecomment-294858022), and then I amended the commit with the version you merged, which I had thought was fixed. But I'd fixed it in the C file but not in the header.

Sorry.

Presumably you have fixed this, or do you want me to add a new patch?

**Comment by MaxKellermann** [comment]
No, it's way too late now. More programs have been built with 2.12+, and we'd break them by changing the order again now.

**Comment by MaxKellermann** [comment]
btw. the order in the C file doesn't matter. It uses C99 designed initializers, and let compiler will reorder them according to the specified index.

**Pull request merged**
